# Generated by Django 4.0.6 on 2024-08-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_checkout_level_remove_checkout_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedoutby',
            name='distribution_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.center'),
            preserve_default=False,
        ),
    ]
